# Generated by Django 4.0.5 on 2023-05-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_files_file_name_remove_files_keywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_name_against_keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=1024)),
                ('keyword', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='keyword_against_file_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=1024)),
                ('keyword', models.CharField(max_length=2024)),
            ],
        ),
    ]
